export type ReviewRating = 'again' | 'hard' | 'good' | 'easy';

export type StudyMode = 'scheduled' | 'cram' | 'practice-test' | 'preview';

export type ReviewStyle =
  | 'concise'
  | 'explanatory'
  | 'visual-support'
  | 'clinical-reasoning'
  | 'test-first';

export type StudyDifficulty = 'gentle' | 'standard' | 'challenging';

export type FeedbackTiming = 'immediate' | 'end';

export type EvidenceDisplay = 'compact' | 'expanded';

export type ExamGoal = 'class-quiz' | 'board-style' | 'clinical-recall' | 'source-mastery';

export type WorkspaceMode = 'learner' | 'builder';

export type StudyProfile = {
  reviewStyle: ReviewStyle;
  difficulty: StudyDifficulty;
  sessionLength: number;
  feedbackTiming: FeedbackTiming;
  evidenceDisplay: EvidenceDisplay;
  dailyNewLimit: number;
  dailyReviewLimit: number;
  examGoal: ExamGoal;
  workspaceMode: WorkspaceMode;
  weeklyStudyDays: number[];
  reminderEnabled: boolean;
  reminderHour: number;
  updatedAt: string;
};

export type TestScope = 'due' | 'all' | 'weak';

export type TestFormat = 'adaptive' | 'rapid-recall' | 'clinical';

export type TestConfidence = 'unsure' | 'confident' | 'easy';

export type CardStatus = 'manual' | 'generated_pending' | 'source_extracted' | 'verified' | 'needs_review';

export type SourceStatus =
  | 'importing'
  | 'parsing'
  | 'generating'
  | 'review-ready'
  | 'ready'
  | 'action-required'
  | 'failed';

export type CandidateStatus = 'pending' | 'approved' | 'rejected';

export type Deck = {
  id: string;
  title: string;
  description: string;
  color: string;
  icon: string;
  createdAt: string;
  updatedAt: string;
  archivedAt?: string | null;
};

export type DeckSummary = Deck & {
  cardCount: number;
  dueCount: number;
  evidenceCount: number;
};

export type StudyCard = {
  id: string;
  deckId: string;
  deckTitle: string;
  prompt: string;
  answer: string;
  cardType: string;
  status: CardStatus;
  isStarred: boolean;
  dueAt: string;
  fsrsCardJson: string;
  lastReviewedAt?: string | null;
  learningObjective?: string | null;
  qualityScore?: number | null;
  qualityNotes?: string | null;
  weakScore?: number;
  isFlagged?: boolean;
  isSuspended?: boolean;
  isLeech?: boolean;
  lapseCount?: number;
  planReason?: 'weak' | 'due' | 'new';
  evidence?: EvidenceSnippet;
};

export type DailyPlan = {
  state: 'ready' | 'resume' | 'complete';
  totalCount: number;
  completedCount: number;
  weakCount: number;
  dueCount: number;
  newCount: number;
  estimatedMinutes: number;
  reason: string;
};

export type CourseModuleSummary = {
  id: string;
  courseId: string;
  title: string;
  position: number;
  deckCount: number;
  cardCount: number;
  deckIds: string[];
};

export type CourseSummary = {
  id: string;
  title: string;
  examDate: string | null;
  color: string;
  moduleCount: number;
  deckCount: number;
  cardCount: number;
  modules: CourseModuleSummary[];
};

export type ActiveStudySession = {
  id: string;
  mode: 'autopilot' | 'deck' | 'weak';
  deckId: string | null;
  focus: string | null;
  planSize: 'normal' | 'minimum';
  totalCount: number;
  completedCount: number;
  createdAt: string;
  cards: StudyCard[];
};

export type EvidenceSnippet = {
  sourceTitle: string;
  locator: string;
  text: string;
  supportScore: number;
  verificationStatus: string;
};

export type SourceItem = {
  id: string;
  title: string;
  filename: string;
  mimeType: string;
  sha256: string;
  localUri: string;
  status: SourceStatus;
  createdAt: string;
  segmentCount: number;
  draftCount: number;
  sourceCardCount: number;
  autoGeneratedCardCount: number;
  autoGeneratedReviewedCardCount: number;
  reviewedCardCount: number;
  defaultDeckId?: string | null;
  defaultDeckTitle?: string | null;
  sizeBytes?: number | null;
  ingestionError?: string | null;
  processedAt?: string | null;
};

export type TrashItem = {
  id: string;
  entityType: 'source' | 'source-cards' | 'deck' | 'card' | 'cards';
  entityId: string;
  title: string;
  itemCount: number;
  reviewedCardCount: number;
  deletedAt: string;
};

export type ArchivedItem = {
  entityType: 'source' | 'deck';
  entityId: string;
  title: string;
  itemCount: number;
  archivedAt: string;
};

export type SourceSegment = {
  id: string;
  sourceId: string;
  locator: string;
  sectionPath: string;
  text: string;
  createdAt: string;
};

export type SourceDetail = SourceItem & {
  segments: SourceSegment[];
  candidates: GeneratedCandidate[];
  generationJob?: GenerationJobSummary;
};

export type GeneratedCandidate = {
  id: string;
  jobId: string;
  segmentId: string | null;
  cardType: string;
  learningObjective: string;
  qualityScore: number;
  qualityNotes: string;
  question: string;
  answer: string;
  evidenceText: string;
  locator: string;
  verificationStatus: string;
  supportScore: number;
  status: CandidateStatus;
  createdAt: string;
};

export type GenerationJobSummary = {
  id: string;
  status: string;
  summary: string;
  createdAt: string;
  updatedAt?: string | null;
};

export type Dashboard = {
  dueCount: number;
  totalCards: number;
  evidenceLinkedCards: number;
  sourceCount: number;
  weakCount: number;
  leechCount: number;
  reviewedToday: number;
  dailyReviewLimit: number;
  sessionLength: number;
  decks: DeckSummary[];
};

export type TestSessionSummary = {
  id: string;
  totalCount: number;
  answeredCount: number;
  correctCount: number;
  createdAt: string;
};

export type ActiveTestSession = TestSessionSummary & {
  deckId: string | null;
  deckTitle: string | null;
  format: TestFormat;
  scope: TestScope;
  questionLimit: number;
  questions: TestQuestion[];
  missedCards: StudyCard[];
};

export type TestOption = {
  id: string;
  label: string;
};

export type TestQuestion = {
  id: string;
  card: StudyCard;
  type: 'multiple-choice' | 'written-recall';
  prompt: string;
  options: TestOption[];
  correctOptionId?: string;
  correctAnswer: string;
};

export type CreateDeckInput = {
  title: string;
  description: string;
  moduleId?: string;
};

export type CreateManualCardInput = {
  deckId: string;
  prompt: string;
  answer: string;
  cardType: string;
};
