import type * as SQLite from 'expo-sqlite';
import { Platform } from 'react-native';

import { createId, nowIso } from '@/domain/ids';
import {
  normalizeSourceStatus,
  type EvidenceSnippet,
  type ReviewRating,
  type SourceItem,
  type StudyCard,
  type StudyMode,
} from '@/domain/types';
import type { GeneratedStudyGuide } from '@/ingestion/studyGuide';
import { applyFsrsReview, schedulerVersion } from '@/scheduler/fsrs';
import { getDatabase } from '@/storage/database';

export type CountRow = { count: number };
export type WritableDatabase = SQLite.SQLiteDatabase;

export type TrashMetadata = {
  sourceId?: string;
  deckId?: string;
  cardIds?: string[];
  noteIds?: string[];
};

export type ImportedCardResult = {
  createdCardCount: number;
  createdNoteCount: number;
  skippedDuplicateCount: number;
  clozeCardCount: number;
};

// Expo SQLite web transactions share one connection. Queue only multi-statement
// repository transactions so a second BEGIN cannot interrupt an active owner.
const writeTransactionTails = new WeakMap<SQLite.SQLiteDatabase, Promise<void>>();

export async function runWriteTransaction(
  db: SQLite.SQLiteDatabase,
  task: (txn: WritableDatabase) => Promise<void>,
) {
  const predecessor = writeTransactionTails.get(db) ?? Promise.resolve();
  const operation = predecessor.catch(() => undefined).then(async () => {
    if (Platform.OS === 'web') {
      await db.withTransactionAsync(async () => task(db));
      return;
    }

    await db.withExclusiveTransactionAsync(task);
  });
  const tail = operation.then(() => undefined, () => undefined);
  writeTransactionTails.set(db, tail);

  try {
    await operation;
  } finally {
    if (writeTransactionTails.get(db) === tail) {
      writeTransactionTails.delete(db);
    }
  }
}

export function localDayStartIso(): string {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  return now.toISOString();
}

export function nextLocalDayIso(from: string): string {
  const date = new Date(from);
  date.setDate(date.getDate() + 1);
  date.setHours(0, 0, 0, 0);
  return date.toISOString();
}

export function normalizeWeeklyStudyDays(days: number[]): number[] {
  const unique = Array.from(new Set(days))
    .filter((day) => Number.isInteger(day) && day >= 0 && day <= 6)
    .sort((a, b) => a - b);
  return unique.length ? unique : [1, 2, 3, 4, 5, 6];
}

export function parseWeeklyStudyDays(value?: string): number[] {
  if (!value) return [1, 2, 3, 4, 5, 6];
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? normalizeWeeklyStudyDays(parsed.map(Number)) : [1, 2, 3, 4, 5, 6];
  } catch {
    return [1, 2, 3, 4, 5, 6];
  }
}

export function normalizeLimit(value: number, maximum: number): number {
  if (value === 0) return 0;
  if (!Number.isFinite(value) || value < 0) return maximum;
  return Math.min(Math.round(value), maximum);
}

export function cardFingerprint(prompt: string, answer: string): string {
  return `${normalizeCardText(prompt)}::${normalizeCardText(answer)}`;
}

export function normalizeCardText(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, ' ');
}

export function compactTitle(value: string): string {
  return value.trim().replace(/\s+/g, ' ').slice(0, 60);
}

export function safeExportName(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'deck';
}

export function hydrateSource(source: SourceItem): SourceItem {
  return {
    ...source,
    status: normalizeSourceStatus(source.status),
    segmentCount: Number(source.segmentCount ?? 0),
    draftCount: Number(source.draftCount ?? 0),
    sourceCardCount: Number(source.sourceCardCount ?? 0),
    autoGeneratedCardCount: Number(source.autoGeneratedCardCount ?? 0),
    autoGeneratedReviewedCardCount: Number(source.autoGeneratedReviewedCardCount ?? 0),
    needsReviewCardCount: Number(source.needsReviewCardCount ?? 0),
    verifiedCardCount: Number(source.verifiedCardCount ?? 0),
    reviewedCardCount: Number(source.reviewedCardCount ?? 0),
    sizeBytes: source.sizeBytes == null ? null : Number(source.sizeBytes),
  };
}

export async function hydrateCards(cards: StudyCard[]): Promise<StudyCard[]> {
  if (!cards.length) return [];

  const db = await getDatabase();
  const placeholders = cards.map(() => '?').join(',');
  const evidenceRows = await db.getAllAsync<EvidenceSnippet & { cardId: string }>(
    `SELECT
       card_evidence.card_id AS cardId,
       sources.title AS sourceTitle,
       source_segments.locator AS locator,
       card_evidence.evidence_text AS text,
       card_evidence.support_score AS supportScore,
       card_evidence.verification_status AS verificationStatus
     FROM card_evidence
     JOIN source_segments ON source_segments.id = card_evidence.segment_id
     JOIN sources ON sources.id = source_segments.source_id
     WHERE card_evidence.card_id IN (${placeholders})
     ORDER BY card_evidence.support_score DESC`,
    cards.map((card) => card.id),
  );
  const evidenceByCard = new Map<string, EvidenceSnippet>();
  for (const row of evidenceRows) {
    if (!evidenceByCard.has(row.cardId)) evidenceByCard.set(row.cardId, row);
  }

  return cards.map((card) => ({
    ...card,
    isStarred: Boolean(card.isStarred),
    isFlagged: Boolean(card.isFlagged),
    isSuspended: Boolean(card.isSuspended),
    isLeech: Boolean(card.isLeech),
    lapseCount: Number(card.lapseCount ?? 0),
    weakScore: Number(card.weakScore ?? 0),
    qualityScore: card.qualityScore == null ? null : Number(card.qualityScore),
    evidence: evidenceByCard.get(card.id),
  }));
}

export async function upsertSearchIndex(db: WritableDatabase, cardId: string) {
  try {
    await db.runAsync('DELETE FROM cards_fts WHERE card_id = ?', cardId);
    await db.runAsync(
      `
      INSERT INTO cards_fts (card_id, deck_id, prompt, answer, deck_title)
      SELECT cards.id, cards.deck_id, cards.prompt, cards.answer, decks.title
      FROM cards
      JOIN decks ON decks.id = cards.deck_id
      WHERE cards.id = ? AND cards.deleted_at IS NULL
      `,
      cardId,
    );
  } catch {
    // FTS can be unavailable on some platforms; LIKE search remains available.
  }
}

export async function upsertCardQuality(
  db: WritableDatabase,
  cardId: string,
  candidate: { learningObjective?: string; qualityScore?: number; qualityNotes?: string },
  checkedAt: string,
) {
  await db.runAsync(
    `INSERT INTO card_quality (card_id, learning_objective, quality_score, quality_notes, checked_at)
     VALUES (?, ?, ?, ?, ?)
     ON CONFLICT(card_id) DO UPDATE SET
       learning_objective = excluded.learning_objective,
       quality_score = excluded.quality_score,
       quality_notes = excluded.quality_notes,
       checked_at = excluded.checked_at`,
    cardId,
    candidate.learningObjective || '',
    Number(candidate.qualityScore ?? 0),
    candidate.qualityNotes || '',
    checkedAt,
  );
}

export async function writeReviewState(
  db: WritableDatabase,
  card: StudyCard,
  rating: ReviewRating,
  responseTimeMs: number,
  studyMode: StudyMode,
  reviewedAt: string,
  makeDueNow = false,
  studySessionId?: string,
) {
  const currentMemory = await db.getFirstAsync<{ fsrsCardJson: string }>(
    'SELECT fsrs_card_json AS fsrsCardJson FROM memory_states WHERE card_id = ?',
    card.id,
  );
  const scheduled = applyFsrsReview(currentMemory?.fsrsCardJson ?? card.fsrsCardJson, rating, new Date(reviewedAt));
  const nextCard = JSON.parse(scheduled.cardJson) as Record<string, unknown>;
  if (makeDueNow) nextCard.due = reviewedAt;
  const cardJson = JSON.stringify(nextCard);
  const dueAt = makeDueNow ? reviewedAt : scheduled.dueAt;

  await db.runAsync(
    `INSERT INTO review_events
     (id, card_id, deck_id, reviewed_at, rating, response_time_ms, study_mode, scheduler_version, study_session_id)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    createId('review'),
    card.id,
    card.deckId,
    reviewedAt,
    rating,
    Math.max(0, Math.round(responseTimeMs)),
    studyMode,
    schedulerVersion,
    studySessionId ?? null,
  );

  await db.runAsync(
    `UPDATE memory_states
     SET fsrs_card_json = ?, difficulty = ?, stability = ?, retrievability = ?,
         due_at = ?, last_reviewed_at = ?, scheduler_version = ?
     WHERE card_id = ?`,
    cardJson,
    scheduled.difficulty,
    scheduled.stability,
    scheduled.retrievability,
    dueAt,
    reviewedAt,
    schedulerVersion,
    card.id,
  );
}

export async function burySiblingCards(db: WritableDatabase, cardId: string, reviewedAt: string) {
  const buriedUntil = nextLocalDayIso(reviewedAt);
  await db.runAsync(
    `INSERT INTO card_learning_state (card_id, buried_until)
     SELECT sibling.id, ?
     FROM cards AS reviewed
     JOIN cards AS sibling ON sibling.note_id = reviewed.note_id AND sibling.id != reviewed.id
     WHERE reviewed.id = ? AND sibling.deleted_at IS NULL
     ON CONFLICT(card_id) DO UPDATE SET buried_until = excluded.buried_until`,
    buriedUntil,
    cardId,
  );
}

export async function upsertSourceStudyGuide(
  db: WritableDatabase,
  sourceId: string,
  guide: GeneratedStudyGuide,
  now: string,
) {
  const existing = await db.getFirstAsync<{ id: string; createdAt: string }>(
    'SELECT id, created_at AS createdAt FROM source_study_guides WHERE source_id = ?',
    sourceId,
  );
  const guideId = existing?.id ?? createId('guide');
  await db.runAsync(
    `INSERT INTO source_study_guides
     (id, source_id, title, overview, outline_json, quick_reference_json, discussion_json, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(source_id) DO UPDATE SET
       title = excluded.title,
       overview = excluded.overview,
       outline_json = excluded.outline_json,
       quick_reference_json = excluded.quick_reference_json,
       discussion_json = excluded.discussion_json,
       updated_at = excluded.updated_at`,
    guideId,
    sourceId,
    guide.title,
    guide.overview,
    JSON.stringify(guide.outline),
    JSON.stringify(guide.quickReference),
    JSON.stringify(guide.discussionQuestions),
    existing?.createdAt ?? now,
    now,
  );
}

export async function resolveRegeneratedCardTrash(db: WritableDatabase, sourceId: string) {
  const items = await db.getAllAsync<{ id: string; metadataJson: string }>(
    `SELECT id, metadata_json AS metadataJson
     FROM library_trash
     WHERE entity_type = 'source-cards'
       AND entity_id = ?
       AND restored_at IS NULL`,
    sourceId,
  );

  for (const item of items) {
    const metadata = JSON.parse(item.metadataJson) as TrashMetadata;
    const cardIds = metadata.cardIds ?? [];
    if (!cardIds.length) continue;
    const placeholders = cardIds.map(() => '?').join(',');
    const remaining = await db.getFirstAsync<CountRow>(
      `SELECT COUNT(*) AS count FROM cards
       WHERE deleted_at IS NOT NULL AND id IN (${placeholders})`,
      cardIds,
    );
    if (Number(remaining?.count ?? 0) === 0) {
      await db.runAsync('UPDATE library_trash SET restored_at = ? WHERE id = ?', nowIso(), item.id);
    }
  }
}
