import * as DocumentPicker from 'expo-document-picker';
import { Directory, File, Paths } from 'expo-file-system';
import { Platform } from 'react-native';
import { createId, nowIso } from '@/domain/ids';
import { normalizeSourceStatus } from '@/domain/types';
import type {
  GenerationJobSummary,
  SourceDetail,
  SourceItem,
  SourceSegment,
  SourceStudyGuide,
  SourceStudyGuideDiscussionQuestion,
  SourceStudyGuideQuickReference,
  SourceStudyGuideSection,
} from '@/domain/types';
import { readSourceAsset } from '@/ingestion/readSource';
import { segmentExtractedPages } from '@/ingestion/segmenter';
import { createStudyGuide, type GeneratedStudyGuide } from '@/ingestion/studyGuide';
import { SourceActionRequiredError, type ParsedSegment, type SourceAssetInput } from '@/ingestion/types';
import { getDatabase } from '@/storage/database';
import { discardPersistedSource, persistImportedSource } from '@/storage/files';
import { colors } from '@/theme/colors';
import { generateLocalFirstStudySetForSource } from './generationRepository';
import { runWriteTransaction, type CountRow, type WritableDatabase } from './shared';

export type SourceStudyGuideRow = {
  id: string;
  sourceId: string;
  title: string;
  overview: string;
  outlineJson: string;
  quickReferenceJson: string;
  discussionJson: string;
  createdAt: string;
  updatedAt: string;
};

export async function getSources(): Promise<SourceItem[]> {
  const db = await getDatabase();

  const sources = await db.getAllAsync<SourceItem>(
    `
    SELECT
      sources.id,
      sources.title,
      sources.filename,
      sources.mime_type AS mimeType,
      sources.sha256,
      sources.local_uri AS localUri,
      sources.size_bytes AS sizeBytes,
      sources.status,
      sources.default_deck_id AS defaultDeckId,
      decks.title AS defaultDeckTitle,
      sources.ingestion_error AS ingestionError,
      sources.processed_at AS processedAt,
      sources.created_at AS createdAt,
      COUNT(source_segments.id) AS segmentCount,
      (
        SELECT COUNT(*)
        FROM generated_candidates
        JOIN generation_jobs ON generation_jobs.id = generated_candidates.job_id
        WHERE generation_jobs.source_id = sources.id
          AND generation_jobs.id = (
            SELECT latest_generation_jobs.id
            FROM generation_jobs AS latest_generation_jobs
            WHERE latest_generation_jobs.source_id = sources.id
            ORDER BY latest_generation_jobs.created_at DESC, latest_generation_jobs.rowid DESC
            LIMIT 1
          )
          AND generated_candidates.status = 'pending'
      ) AS draftCount
      ,(
        SELECT COUNT(*)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        WHERE notes.source_id = sources.id
          AND cards.deleted_at IS NULL
      ) AS sourceCardCount
      ,(
        SELECT COUNT(*)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        WHERE notes.source_id = sources.id
          AND (
            cards.status = 'source_extracted'
            OR EXISTS (
              SELECT 1 FROM generated_candidates
              WHERE generated_candidates.published_card_id = cards.id
            )
          )
          AND cards.deleted_at IS NULL
      ) AS autoGeneratedCardCount
      ,(
        SELECT COUNT(DISTINCT cards.id)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        JOIN review_events ON review_events.card_id = cards.id
        WHERE notes.source_id = sources.id
          AND (
            cards.status = 'source_extracted'
            OR EXISTS (
              SELECT 1 FROM generated_candidates
              WHERE generated_candidates.published_card_id = cards.id
            )
          )
          AND cards.deleted_at IS NULL
          AND review_events.reverted_at IS NULL
      ) AS autoGeneratedReviewedCardCount
      ,(
        SELECT COUNT(*)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        WHERE notes.source_id = sources.id
          AND cards.status = 'needs_review'
          AND cards.deleted_at IS NULL
      ) AS needsReviewCardCount
      ,(
        SELECT COUNT(*)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        WHERE notes.source_id = sources.id
          AND cards.status = 'verified'
          AND cards.deleted_at IS NULL
      ) AS verifiedCardCount
      ,(
        SELECT COUNT(DISTINCT cards.id)
        FROM cards
        JOIN review_events ON review_events.card_id = cards.id
        WHERE cards.deck_id = sources.default_deck_id
          AND cards.deleted_at IS NULL
          AND review_events.reverted_at IS NULL
      ) AS reviewedCardCount
    FROM sources
    LEFT JOIN source_segments ON source_segments.source_id = sources.id
    LEFT JOIN decks ON decks.id = sources.default_deck_id
    WHERE sources.deleted_at IS NULL AND sources.archived_at IS NULL
    GROUP BY sources.id
    ORDER BY sources.created_at DESC
    `,
  );

  return sources.map(hydrateSource);
}

export async function getSourceDetail(sourceId: string): Promise<SourceDetail | null> {
  const db = await getDatabase();
  const source = await db.getFirstAsync<SourceItem>(
    `
    SELECT
      sources.id,
      sources.title,
      sources.filename,
      sources.mime_type AS mimeType,
      sources.sha256,
      sources.local_uri AS localUri,
      sources.size_bytes AS sizeBytes,
      sources.status,
      sources.default_deck_id AS defaultDeckId,
      decks.title AS defaultDeckTitle,
      sources.ingestion_error AS ingestionError,
      sources.processed_at AS processedAt,
      sources.created_at AS createdAt,
      COUNT(source_segments.id) AS segmentCount,
      (
        SELECT COUNT(*)
        FROM generated_candidates
        JOIN generation_jobs ON generation_jobs.id = generated_candidates.job_id
        WHERE generation_jobs.source_id = sources.id
          AND generation_jobs.id = (
            SELECT latest_generation_jobs.id
            FROM generation_jobs AS latest_generation_jobs
            WHERE latest_generation_jobs.source_id = sources.id
            ORDER BY latest_generation_jobs.created_at DESC, latest_generation_jobs.rowid DESC
            LIMIT 1
          )
          AND generated_candidates.status = 'pending'
      ) AS draftCount
      ,(
        SELECT COUNT(*)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        WHERE notes.source_id = sources.id
          AND cards.deleted_at IS NULL
      ) AS sourceCardCount
      ,(
        SELECT COUNT(*)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        WHERE notes.source_id = sources.id
          AND (
            cards.status = 'source_extracted'
            OR EXISTS (
              SELECT 1 FROM generated_candidates
              WHERE generated_candidates.published_card_id = cards.id
            )
          )
          AND cards.deleted_at IS NULL
      ) AS autoGeneratedCardCount
      ,(
        SELECT COUNT(DISTINCT cards.id)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        JOIN review_events ON review_events.card_id = cards.id
        WHERE notes.source_id = sources.id
          AND (
            cards.status = 'source_extracted'
            OR EXISTS (
              SELECT 1 FROM generated_candidates
              WHERE generated_candidates.published_card_id = cards.id
            )
          )
          AND cards.deleted_at IS NULL
          AND review_events.reverted_at IS NULL
      ) AS autoGeneratedReviewedCardCount
      ,(
        SELECT COUNT(*)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        WHERE notes.source_id = sources.id
          AND cards.status = 'needs_review'
          AND cards.deleted_at IS NULL
      ) AS needsReviewCardCount
      ,(
        SELECT COUNT(*)
        FROM cards
        JOIN notes ON notes.id = cards.note_id
        WHERE notes.source_id = sources.id
          AND cards.status = 'verified'
          AND cards.deleted_at IS NULL
      ) AS verifiedCardCount
      ,(
        SELECT COUNT(DISTINCT cards.id)
        FROM cards
        JOIN review_events ON review_events.card_id = cards.id
        WHERE cards.deck_id = sources.default_deck_id
          AND cards.deleted_at IS NULL
          AND review_events.reverted_at IS NULL
      ) AS reviewedCardCount
    FROM sources
    LEFT JOIN source_segments ON source_segments.source_id = sources.id
    LEFT JOIN decks ON decks.id = sources.default_deck_id
    WHERE sources.id = ? AND sources.deleted_at IS NULL AND sources.archived_at IS NULL
    GROUP BY sources.id
    `,
    sourceId,
  );

  if (!source) {
    return null;
  }

  const segments = await db.getAllAsync<SourceSegment>(
    `
    SELECT
      id,
      source_id AS sourceId,
      locator,
      section_path AS sectionPath,
      text,
      created_at AS createdAt
    FROM source_segments
    WHERE source_id = ?
    ORDER BY created_at ASC
    `,
    sourceId,
  );

  const generationJobRow = await db.getFirstAsync<GenerationJobSummary>(
    `
    SELECT
      id,
      status,
      summary,
      generation_mode AS generationMode,
      provider_id AS providerId,
      model_id AS modelId,
      attempted_provider_id AS attemptedProviderId,
      attempted_model_id AS attemptedModelId,
      prompt_id AS promptId,
      prompt_version AS promptVersion,
      request_id AS requestId,
      provider_request_id AS providerRequestId,
      input_tokens AS inputTokens,
      output_tokens AS outputTokens,
      fallback_reason AS fallbackReason,
      fallback_used AS fallbackUsed,
      failure_reason AS failureReason,
      remote_candidate_count AS remoteCandidateCount,
      published_card_count AS publishedCardCount,
      held_candidate_count AS heldCandidateCount,
      attempt_count AS attemptCount,
      next_attempt_at AS nextAttemptAt,
      duration_ms AS durationMs,
      created_at AS createdAt,
      updated_at AS updatedAt
    FROM generation_jobs
    WHERE source_id = ?
    ORDER BY created_at DESC, rowid DESC
    LIMIT 1
    `,
    sourceId,
  );
  const generationJob = generationJobRow
    ? {
        ...generationJobRow,
        fallbackUsed: Boolean(generationJobRow.fallbackUsed),
        remoteCandidateCount: Number(generationJobRow.remoteCandidateCount ?? 0),
        publishedCardCount: Number(generationJobRow.publishedCardCount ?? 0),
        heldCandidateCount: Number(generationJobRow.heldCandidateCount ?? 0),
        attemptCount: Number(generationJobRow.attemptCount ?? 0),
        durationMs: generationJobRow.durationMs === null || generationJobRow.durationMs === undefined
          ? null
          : Number(generationJobRow.durationMs),
      }
    : undefined;

  const guideRow = await db.getFirstAsync<SourceStudyGuideRow>(
    `
    SELECT
      id,
      source_id AS sourceId,
      title,
      overview,
      outline_json AS outlineJson,
      quick_reference_json AS quickReferenceJson,
      discussion_json AS discussionJson,
      created_at AS createdAt,
      updated_at AS updatedAt
    FROM source_study_guides
    WHERE source_id = ?
    LIMIT 1
    `,
    sourceId,
  );
  const studyGuide = guideRow
    ? hydrateStudyGuide(guideRow)
    : segments.length
      ? fallbackStudyGuide(sourceId, source.title, segments)
      : undefined;

  return {
    ...hydrateSource(source),
    segments,
    generationJob,
    studyGuide,
  };
}

type TrashMetadata = {
  sourceId?: string;
  deckId?: string;
  cardIds?: string[];
  noteIds?: string[];
};


async function importSourceAsset(asset: SourceAssetInput, customTitle?: string) {
  if (asset.size && asset.size > 30 * 1024 * 1024) {
    throw new Error('This file is larger than 30 MB. Split it into a focused chapter and try again.');
  }
  const now = nowIso();
  const db = await getDatabase();
  const sourceId = createId('src');
  const deckId = createId('deck');
  const sourceTitle = customTitle || asset.name.replace(/\.[^/.]+$/, '').trim() || 'Imported study set';
  const stored = await persistImportedSource(sourceId, asset);

  const existing = await db.getFirstAsync<{ id: string; localUri: string; status: string }>(
    `SELECT id, local_uri AS localUri, status
     FROM sources
     WHERE sha256 = ? AND deleted_at IS NULL AND archived_at IS NULL
     ORDER BY created_at ASC
     LIMIT 1`,
    stored.sha256,
  );
  if (existing) {
    if (existing.status === 'action-required' || existing.status === 'failed') {
      await db.runAsync(
        `UPDATE sources
         SET local_uri = ?, mime_type = ?, size_bytes = ?, ingestion_error = NULL
         WHERE id = ?`,
        stored.localUri,
        asset.mimeType ?? 'application/octet-stream',
        stored.sizeBytes,
        existing.id,
      );
      await prepareSource(existing.id, { ...asset, uri: stored.localUri });
      void generateLocalFirstStudySetForSource(existing.id).catch((err) => {
        console.warn('Background card generation error:', err);
      });
    } else {
      discardPersistedSource(stored.localUri);
    }
    return { sourceId: existing.id, duplicate: true };
  }

  await runWriteTransaction(db, async (txn) => {
    await txn.runAsync(
      `INSERT INTO decks (id, title, description, color, icon, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      deckId,
      sourceTitle,
      `Automatically created from ${asset.name}.`,
      colors.blue,
      'document-text-outline',
      now,
      now,
    );
    await txn.runAsync(
      `INSERT INTO sources
       (id, title, filename, mime_type, sha256, local_uri, size_bytes, status, default_deck_id, ingestion_error, processed_at, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      sourceId,
      sourceTitle,
      asset.name,
      asset.mimeType ?? 'application/octet-stream',
      stored.sha256,
      stored.localUri,
      stored.sizeBytes,
      'importing',
      deckId,
      null,
      null,
      now,
    );

    await txn.runAsync(
      `INSERT INTO sync_operations
       (id, entity_type, entity_id, operation, payload_json, status, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      createId('sync'),
      'source',
      sourceId,
      'create',
      JSON.stringify({ sourceId, filename: asset.name }),
      'local-only',
      now,
    );
  });

  await prepareSource(sourceId, {
    ...asset,
    uri: stored.localUri,
  });
  void generateLocalFirstStudySetForSource(sourceId).catch((err) => {
    console.warn('Background card generation error:', err);
  });

  return { sourceId, duplicate: false };
}

export async function importSourceFromPicker(allowedTypes?: ('pdf' | 'text')[]) {
  const mimeTypes = allowedTypes?.includes('pdf') && !allowedTypes?.includes('text')
    ? ['application/pdf']
    : allowedTypes?.includes('text') && !allowedTypes?.includes('pdf')
      ? ['text/plain', 'text/markdown']
      : ['application/pdf', 'text/plain', 'text/markdown'];

  const picked = await DocumentPicker.getDocumentAsync({
    base64: false,
    copyToCacheDirectory: true,
    multiple: false,
    type: mimeTypes,
  });

  if (picked.canceled || !picked.assets[0]) {
    return null;
  }

  const asset = picked.assets[0];
  return importSourceAsset({
    name: asset.name,
    uri: asset.uri,
    mimeType: asset.mimeType,
    size: asset.size,
    file: asset.file,
  });
}

export async function importSourceFromText(title: string, text: string) {
  const trimmed = text.trim();
  if (!trimmed) {
    throw new Error('Please enter or paste study notes.');
  }

  const cleanTitle = title.trim() || 'Pasted notes';
  const safeFilename = cleanTitle.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'notes';
  const filename = `${safeFilename}.txt`;

  let asset: SourceAssetInput;
  if (Platform.OS === 'web') {
    const blob = new Blob([trimmed], { type: 'text/plain;charset=utf-8' });
    asset = {
      name: filename,
      uri: `data:text/plain;charset=utf-8,${encodeURIComponent(trimmed)}`,
      mimeType: 'text/plain',
      size: blob.size,
      file: blob,
    };
  } else {
    const directory = new Directory(Paths.cache, 'medstudy-imports');
    directory.create({ idempotent: true, intermediates: true });
    const tempFile = new File(directory, `${createId('note')}-${filename}`);
    tempFile.create();
    tempFile.write(trimmed);
    asset = {
      name: filename,
      uri: tempFile.uri,
      mimeType: 'text/plain',
      size: tempFile.size ?? trimmed.length,
    };
  }

  return importSourceAsset(asset, cleanTitle);
}

export async function retrySourceProcessing(sourceId: string) {
  const db = await getDatabase();
  const source = await db.getFirstAsync<{
    filename: string;
    mimeType: string;
    localUri: string;
    sizeBytes: number | null;
  }>(
    `SELECT filename, mime_type AS mimeType, local_uri AS localUri, size_bytes AS sizeBytes
     FROM sources
     WHERE id = ? AND deleted_at IS NULL AND archived_at IS NULL`,
    sourceId,
  );

  if (!source) {
    throw new Error('Source not found.');
  }

  return processSource(sourceId, {
    name: source.filename,
    mimeType: source.mimeType,
    uri: source.localUri,
    size: source.sizeBytes,
  });
}

export async function refreshStudyGuideForSource(sourceId: string) {
  const db = await getDatabase();
  const source = await db.getFirstAsync<{ id: string; title: string }>(
    `SELECT id, title
     FROM sources
     WHERE id = ? AND deleted_at IS NULL AND archived_at IS NULL`,
    sourceId,
  );
  if (!source) {
    throw new Error('Source not found.');
  }

  const segments = await db.getAllAsync<ParsedSegment>(
    `SELECT
       id,
       locator,
       section_path AS sectionPath,
       text,
       COALESCE(start_offset, 0) AS startOffset,
       COALESCE(end_offset, length(text)) AS endOffset
     FROM source_segments
     WHERE source_id = ?
     ORDER BY created_at ASC`,
    sourceId,
  );
  if (!segments.length) {
    throw new Error('Extract this source before creating a study guide.');
  }

  const now = nowIso();
  const guide = createStudyGuide(segments, source.title);
  await runWriteTransaction(db, async (txn) => {
    await upsertSourceStudyGuide(txn, sourceId, guide, now);
  });
  return guide;
}


async function upsertSourceStudyGuide(
  db: WritableDatabase,
  sourceId: string,
  guide: GeneratedStudyGuide,
  now: string,
) {
  const existing = await db.getFirstAsync<{ id: string; createdAt: string }>(
    'SELECT id, created_at AS createdAt FROM source_study_guides WHERE source_id = ?',
    sourceId,
  );
  const guideId = existing?.id ?? createId('guide');
  await db.runAsync(
    `INSERT INTO source_study_guides
     (id, source_id, title, overview, outline_json, quick_reference_json, discussion_json, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(source_id) DO UPDATE SET
       title = excluded.title,
       overview = excluded.overview,
       outline_json = excluded.outline_json,
       quick_reference_json = excluded.quick_reference_json,
       discussion_json = excluded.discussion_json,
       updated_at = excluded.updated_at`,
    guideId,
    sourceId,
    guide.title,
    guide.overview,
    JSON.stringify(guide.outline),
    JSON.stringify(guide.quickReference),
    JSON.stringify(guide.discussionQuestions),
    existing?.createdAt ?? now,
    now,
  );
}

function hydrateStudyGuide(row: SourceStudyGuideRow): SourceStudyGuide {
  return {
    id: row.id,
    sourceId: row.sourceId,
    title: row.title,
    overview: row.overview,
    outline: parseGuideArray<SourceStudyGuideSection>(row.outlineJson),
    quickReference: parseGuideArray<SourceStudyGuideQuickReference>(row.quickReferenceJson),
    discussionQuestions: parseGuideArray<SourceStudyGuideDiscussionQuestion>(row.discussionJson),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function fallbackStudyGuide(sourceId: string, title: string, segments: SourceSegment[]): SourceStudyGuide {
  const generated = createStudyGuide(
    segments.map((segment) => ({
      id: segment.id,
      locator: segment.locator,
      sectionPath: segment.sectionPath,
      text: segment.text,
      startOffset: 0,
      endOffset: segment.text.length,
    })),
    title,
  );
  const now = nowIso();
  return {
    id: `guide-${sourceId}`,
    sourceId,
    title: generated.title,
    overview: generated.overview,
    outline: generated.outline,
    quickReference: generated.quickReference,
    discussionQuestions: generated.discussionQuestions,
    createdAt: now,
    updatedAt: now,
  };
}

function parseGuideArray<T>(serialized: string): T[] {
  try {
    const parsed = JSON.parse(serialized);
    return Array.isArray(parsed) ? parsed as T[] : [];
  } catch {
    return [];
  }
}

export async function prepareSource(sourceId: string, asset: SourceAssetInput) {
  const db = await getDatabase();
  const source = await db.getFirstAsync<{ title: string }>(
    'SELECT title FROM sources WHERE id = ? AND deleted_at IS NULL AND archived_at IS NULL',
    sourceId,
  );
  if (!source) {
    throw new Error('Source not found.');
  }

  await db.runAsync(
    "UPDATE sources SET status = 'parsing', ingestion_error = NULL WHERE id = ?",
    sourceId,
  );

  try {
    const pages = await readSourceAsset(asset);
    const segments = segmentExtractedPages(pages, source.title);
    if (!segments.length) {
      throw new SourceActionRequiredError(
        'Barion could read the file, but there was not enough continuous text to create study material.',
      );
    }

    const processedAt = nowIso();
    const studyGuide = createStudyGuide(segments, source.title);
    await runWriteTransaction(db, async (txn) => {
      await txn.runAsync('DELETE FROM source_segments WHERE source_id = ?', sourceId);

      for (const segment of segments) {
        await txn.runAsync(
          `INSERT INTO source_segments
           (id, source_id, locator, section_path, text, start_offset, end_offset, created_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
          segment.id,
          sourceId,
          segment.locator,
          segment.sectionPath,
          segment.text,
          segment.startOffset,
          segment.endOffset,
          processedAt,
        );
      }

      await upsertSourceStudyGuide(txn, sourceId, studyGuide, processedAt);

      await txn.runAsync(
        `UPDATE sources
         SET status = 'generating', ingestion_error = NULL, processed_at = ?
         WHERE id = ?`,
        processedAt,
        sourceId,
      );
    });

    return { segmentCount: segments.length };
  } catch (error) {
    const status = error instanceof SourceActionRequiredError ? 'action-required' : 'failed';
    const message = error instanceof Error ? error.message : 'Barion could not process this source.';
    await db.runAsync(
      'UPDATE sources SET status = ?, ingestion_error = ? WHERE id = ?',
      status,
      message,
      sourceId,
    );
    return { segmentCount: 0, draftCount: 0 };
  }
}

export async function processSource(sourceId: string, asset: SourceAssetInput) {
  const prepared = await prepareSource(sourceId, asset);
  if (prepared.segmentCount === 0) {
    return { segmentCount: 0, draftCount: 0 };
  }
  const draftCount = await generateLocalFirstStudySetForSource(sourceId);
  return { segmentCount: prepared.segmentCount, draftCount };
}

function hydrateSource(source: SourceItem): SourceItem {
  return {
    ...source,
    status: normalizeSourceStatus(source.status),
    segmentCount: Number(source.segmentCount ?? 0),
    draftCount: Number(source.draftCount ?? 0),
    sourceCardCount: Number(source.sourceCardCount ?? 0),
    autoGeneratedCardCount: Number(source.autoGeneratedCardCount ?? 0),
    autoGeneratedReviewedCardCount: Number(source.autoGeneratedReviewedCardCount ?? 0),
    needsReviewCardCount: Number(source.needsReviewCardCount ?? 0),
    verifiedCardCount: Number(source.verifiedCardCount ?? 0),
    reviewedCardCount: Number(source.reviewedCardCount ?? 0),
    sizeBytes: source.sizeBytes == null ? null : Number(source.sizeBytes),
  };
}
